server:
  port: 8085
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/ceo
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/ceo
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service
            client-secret: rgYzQHuURkdrS40kQsWSnc9Aruo0VqGT
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: admin-service
            client-secret: rgYzQHuURkdrS40kQsWSnc9Aruo0VqGT

management:
  endpoints:
    web:
      exposure:
        exclude:
          - health
          - prometheus