ceo:
  services:
    catalogue:
      uri: http://localhost:8081
      registration-id: keycloak
    feedback:
      uri: http://localhost:8084

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    username: igor
    password: ni30uywiw
    url: jdbc:postgresql://localhost:5432/manager

  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: manager-app
            client-secret: JwByKV4Y8m95GDYTNqJH6jfaj5dXpv8F
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt

        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
            user-name-attribute: preferred_username
server:
  port: 8080

file:
  path: ${user.dir}/manage-app/src/main/resources/static/imgs

