server:
  port: 8084
spring:
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      uri: mongodb://localhost:27017/feedback

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
