ceo:
  services:
    catalogue:
      uri: http://localhost:8081
    feedback:
      uri: http://localhost:8084
server:
  port: 8083
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: customer-app
            client-secret: M1bhGCByxWDqVWeokJj6Z9sMGTI41lNc
            scope:
              - openid
              - view_catalogue

        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/ceo
            user-name-attribute: preferred_username



